eureka:
  instance:
    preferIpAddress: false
    non-secure-port-enabled: true
    secure-port-enabled: false
    non-secure-port: ${server.port}
    secure-port: 443

server:
  tomcat:
    max-threads: 20
    min-spare-threads: 5

spring:
  main:
    lazy-initialization: true