server:
  port: ${PORT:8080}

eureka:
  instance:
    preferIpAddress: false
    hostname: ms-elastic-tfm-production.up.railway.app
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    status-page-url: https://${eureka.instance.hostname}/actuator/info
    health-check-url: https://${eureka.instance.hostname}/actuator/health
    home-page-url: https://${eureka.instance.hostname}/
