## Configuracion de Spring
spring:
  application:
    name: ms-elastic-tfm
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchRestClientAutoConfiguration

## Configuracion de Instancia
server:
  port: 8087
  fullAddress: ${HOST:http://localhost}:${PORT:${server.port}}

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-elastic-tfm

##Elasticsearch config
elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  credentials:
    user: ${ELASTICSEARCH_USER}
    password: ${ELASTICSEARCH_PWD}

logging:
  level:
    tracer: TRACE
    org.springframework.data.elasticsearch: DEBUG
