## Configuracion de Spring
spring:
  application:
    name: ms-elastic-tfm
  security:
    oauth2:
      resourceserver:
        jwt: {}

## Configuracion de Instancia
server:
  port: ${PORT:8080}
  fullAddress: ${HOST:http://localhost}:${PORT:${server.port}}

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-elastic-tfm

##Elasticsearch config
elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  credentials:
    user: ${ELASTICSEARCH_USER}
    password: ${ELASTICSEARCH_PWD}
  security:
    jwt:
      secret-key: ${JWT_SECRET:changeme}
      issuer: ${JWT_ISSUER}
      audience: ${JWT_AUDIENCE}

logging:
  level:
    tracer: TRACE
    org.springframework.data.elasticsearch: DEBUG

simulator:
  allowed-email: ${ALLOWED-EMAIL}
  secret-header-name: ${SECRET-HEADER-NAME}
  secret-header-value: ${SECRET-HEADER-VALUE}