## Configuracion de Spring
spring:
  application:
    name: ms-elastic-tfm
  security:
    oauth2:
      resourceserver:
        jwt: {}

## Configuracion de Instancia
server:
  port: ${PORT:8080}
  fullAddress: ${HOST:http://localhost}:${PORT:${server.port}}

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-elastic-tfm

##Elasticsearch config
elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  credentials:
    user: ${ELASTICSEARCH_USER}
    password: ${ELASTICSEARCH_PWD}
  security:
    jwt:
      secret-key: ${JWT_SECRET:changeme}
      issuer: ${JWT_ISSUER}
      audience: ${JWT_AUDIENCE}

logging:
  level:
    root: INFO
    org.springframework.data.elasticsearch: INFO
    co.elastic.clients: INFO
    tracer: OFF
    sun.rmi: OFF
    javax.management: OFF

simulator:
  allowed-email: ${ALLOWED_EMAIL}
  secret-header-name: ${SECRET_HEADER_NAME}
  secret-header-value: ${SECRET_HEADER_VALUE}