server:
  port: ${PORT:8080}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ms-elastic-tfm-production.up.railway.app
    status-page-url: https://${eureka.instance.hostname}/actuator/info
    health-check-url: https://${eureka.instance.hostname}/actuator/health
    home-page-url: https://${eureka.instance.hostname}/
